sudo: false
language: node_js
node_js:
- '6.0'
before_deploy: npm run build
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pierre.besson7+npm@gmail.com
  api_key:
    secure: kLd1pxg5fQjoTKDzpbniGP61JD0UeVYIUbXlBokZmCcWf359tdmDhIjA0fEZiP2LiSYiC51Z6egamgykNSI+fI7KhylR9Y2q/S+rqjd3g0/TedDp+jHnZVTTX7tP7q5wlfUZqR1Llr24i3rdXGpg/laXjuK+OtnbgTsjNecS1Gq0P/JOcGX9SHmgNlZyTpgOJt7c0QjRDqtjnawyjLnkmth5syQ2GyhCedOt58wNWVyRYy2K7muO7aboNdlBEea7zLwWNVtfNxeCOljQ792urUEIXXQ3rv/s0aYu6QSWToMkawl98gGSfgCXK/5KUX0WEzF35ik5XgslSh8Sd2LUF76rNDwIIgsCH9d/FlEZUlPsP10uB+aj5nKjft8rwlYSws2ljopW/f3fKLbrpuiFK9NsC2cxnNGr9tyUB93DH92S2PyigKY10MS8/UMFFEx11k0VWgopzWmA3+e4kmsALBTIC94aDyRCqP3auB5j5CJ8TLUN+pFLSdxUWMI5oPwYvmXz7DCMyK5CKhwxJQGReXAwc+JRfzgLjTGTWUtBQ+IeFeMbl04be2iOcaJVj59KOOowiqK66R/OgehjmoO9R18495SD2n2jkowWiVV34M/DoXhugpDmEWOfRBukrvoPA2nec/kv9fjE1Rqys/FjEAdjdU6RBqUj47jgsUhpjLg=
  on:
    repo: KleeGroup/focus-file
